name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", 3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install pylint
    - name: Build package
      run: |
        python -m build
    - name: Install as package
      run: |
        pip install pylint
        pip install .
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under=9.2 --extension-pkg-whitelist=cv2 --generated-members=cv2
